# Digital Twin Configuration

# LLM Configuration
llm:
  provider: "openai"  # Options: openai, anthropic, huggingface, local
  model: "gpt-4"  # Model name/identifier
  temperature: 0.7
  max_tokens: 1000
  top_p: 0.9
  top_k: 50
  repetition_penalty: 1.2

# Memory Configuration
memory:
  max_memories: 1000
  relevance_threshold: 0.7
  memory_types:
    - short_term
    - long_term
    - episodic
    - semantic

# Personality Configuration
personality:
  traits:
    openness: 0.7
    conscientiousness: 0.8
    extraversion: 0.6
    agreeableness: 0.75
    neuroticism: 0.3
  response_style:
    formality_level: 0.8
    enthusiasm_level: 0.6
    politeness_level: 0.9

# Server Configuration
server:
  host: "localhost"
  port: 8000
  debug: true
  cors_origins: ["*"]

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "digital_twin.log" 